spring:
  cassandra:
    contact-points: localhost
    port: 9042
    keyspace-name: feed_app
    schema-action: CREATE_IF_NOT_EXISTS
    connection:
      connect-timeout: 5s
      init-query-timeout: 5s
    local-datacenter: datacenter1
