spring:
  r2dbc:
    url: r2dbc:h2:mem:///testdb;MODE=MySQL;DATABASE_TO_LOWER=TRUE
    username: sa
    password:

  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
  h2:
    console:
      enabled: true

logging:
  level:
    org.springframework.r2dbc: DEBUG
