server:
    port: 8084
spring:
  cassandra:
    contact-points: localhost
    port: 9042
    keyspace-name: feed_app
    schema-action: CREATE_IF_NOT_EXISTS
    connection:
      connect-timeout: 5s
      init-query-timeout: 5s
    local-datacenter: datacenter1
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  snowflake:
    urls: http://localhost:9713
jwt:
    secret: 24675e854c23f198b53695053c65ce96089e1e3f77ea43104f1a30e21406fa9c
