server:
  port: 8085

spring:
  application:
    name: batch-app
  cassandra:
    contact-points: localhost
    port: 9042
    keyspace-name: user_app
    schema-action: CREATE_IF_NOT_EXISTS
    connection:
      connect-timeout: 5s
      init-query-timeout: 5s
    local-datacenter: datacenter1
  data:
    redis:
      host: localhost
      port: 6379
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: batch-follow-count-sync
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false  # Prevent auto-run on startup
  quartz:
    job-store-type: memory
    properties:
      org:
        quartz:
          threadPool:
            threadCount: 5

batch:
  news-feed-cache:
    max-items: 50
  follow-count-sync:
    chunk-size: 100

kafka:
  topic:
    follow-count-sync: follow-count-sync