spring:
  application:
    name: gateway-app
  data:
    redis:
      host: localhost
      port: 6379
  session:
    store-type: redis
    redis:
      namespace: spring:session

server:
  port: 8080

jwt:
  secret: 24675e854c23f198b53695053c65ce96089e1e3f77ea43104f1a30e21406fa9c
  expiration-ms: 3600000

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
  endpoint:
    gateway:
      enabled: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty: DEBUG
