services:
  redis_container:
    image: redis:7.4.2
    container_name: redis
    ports:
      - '6379:6379'
    labels:
      - "name=redis"
      - "mode=standalone"
    restart: always
    command: redis-server